import Head from 'next/head'
import Image from 'next/image'
import { Caprasimo, Fira_Mono, Abhaya_Libre } from 'next/font/google'
import styles from '@/styles/Home.module.css'
import Draggable from 'react-draggable'; 

const caprisimo = Caprasimo({ subsets: ['latin'], weight: "400" })
const fira_mono = Fira_Mono({ subsets: ['latin'], weight: ["400", "500", "700"] })
const abhaya_libre = Abhaya_Libre({subsets:['latin'], weight: ["400", "500", "600", "700", "800"]})

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${caprisimo.className}`}>
        <div className={styles.grid}>
            <div className={styles.backgroundwrapper}>
                <div className={styles.background}>
                    <Image
                    src={require("/assets/maroonbg.png")}
                    fill={true}
                    style={{objectFit: "cover"}}
                    alt="background"
                    />
                </div>
            </div>
            <Draggable>
                <div className={styles.banner}>

                        <Image
                        src={require("/assets/banner.png")}
                        fill={true}
                        style={{objectFit: "cover"}}
                        alt="banner"
                        draggable={false}
                        />
  
                </div>
            </Draggable>
            <Draggable>
                <div className={`${styles.header} ${abhaya_libre.className}`} > 
                    <h1> platform for yo<span>uth creativity</span></h1>
                </div>
            </Draggable>
        </div>
      </main>
    </>
  )
}
